# Generated by Django 5.2.4 on 2025-07-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('nickname', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=19)),
                ('type', models.CharField(choices=[('PF', 'Individual'), ('PJ', 'Company')], default='PF', max_length=2)),
                ('general_registry', models.CharField(blank=True, max_length=15, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('addresses', models.ManyToManyField(related_name='clients', to='adress.adress')),
            ],
        ),
    ]
