# Generated by Django 5.2.4 on 2025-07-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='addresses',
            new_name='adresses',
        ),
    ]
