# Generated by Django 5.2.4 on 2025-07-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_phone_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='client',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
