# Generated by Django 5.2.4 on 2025-07-16 14:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0005_remove_phone_client_delete_email_delete_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de telefone inválido. Exemplo: (11) 91234-5678', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='client.client')),
            ],
        ),
    ]
