# Generated by Django 5.2.4 on 2025-07-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MA', 'Main Adress'), ('AA', 'Alternative Adress')], default='MA', max_length=2)),
                ('state_registration', models.CharField(blank=True, max_length=20, null=True)),
                ('postal_code', models.CharField(max_length=9)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('address_complement', models.CharField(blank=True, max_length=50, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('area_code', models.CharField(blank=True, max_length=3, null=True)),
                ('state_abbr', models.CharField(blank=True, max_length=2, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('ibge_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
